username: libo
#username: gzhennaxia

spring:
  profiles:
    active: dev

  datasource:
    primary: # 主数据源
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/gzhennaxia
      username: root
      password: 88888888

    annotation: # 笔记对应的数据源
      driver-class-name: org.sqlite.JDBC
      jdbc-url: jdbc:sqlite:/Users/${username}/Library/Containers/com.apple.iBooksX/Data/Documents/AEAnnotation/AEAnnotation_v10312011_1727_local.sqlite
      username:
      password:

    library: # 书库对应的数据源
      driver-class-name: org.sqlite.JDBC
      jdbc-url: jdbc:sqlite:/Users/${username}/Library/Containers/com.apple.iBooksX/Data/Documents/BKLibrary/BKLibrary-1-091020131601.sqlite
      username:
      password:

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true